[package]
name = "neige_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neige_infra = { version = "0.1.0", workspace = true }
neige_undump = { version = "0.1.0", workspace = true }
