/// lua token枚举
#[allow(dead_code)]
pub enum LuaToken {
    And,          // and
    Break,        // break
    Do,           // do
    Else,         // else
    Elseif,       // else-if
    End,          // end
    False,        // flase
    For,          // for
    Function,     // function
    Goto,         // goto
    If,           // if
    In,           // in
    Local,        // local
    Nil,          // nil
    Not,          // not
    Or,           // or
    Repeat,       // repeat
    Return,       // return
    Then,         // then
    True,         // true
    Until,        // until
    While,        // while
    Add,          // +
    Sub,          // -
    Mul,          // *
    Div,          // /
    Mod,          // %
    Pow,          // ^
    Len,          // #
    BitAnd,       // &
    BitNot,       // ~
    BitOr,        // |
    ShiftL,       // <<
    ShiftR,       // >>
    IDiv,         // //
    Equal,        // ==
    NotEq,        // !=
    LesEq,        // <=
    GreEq,        // >=
    Less,         // <
    Greater,      // >
    Assign,       // =
    ParL,         // (
    ParR,         // )
    CurlyL,       // {
    CurlyR,       // }
    SqurL,        // [
    SqurR,        // ]
    DoubleColon,  // ::
    SemiColon,    // ;
    Colon,        // :
    Comma,        // ,
    Dot,          // .
    Concat,       // ..
    Dots,         // ...
    Integer(i64), // 整数
    Float(f64),   // 浮点数
    Str(String),  // 字符串
    Name(String), // 标识符
    Eos,          // 结束符
}
